import Head from 'next/head'
import styled from "styled-components";
import * as GooglePhotosAlbum from "google-photos-album-image-url-fetch";
import ImageCard from "../components/ImageCard";


export async function getStaticProps (context) {
  const images = await GooglePhotosAlbum.fetchImageUrls(process.env.GOOGLE_PHOTOS_SHARE_URL);
  return {
    props: {
      images
    },
  }
}

export default function Home ({ images }) {
  return (
    <Root>
      <Head>
        <title>Google Photos gallery</title>
        <meta name="description" content="Generated by create next app"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <Main>
        {images.map(e => (
          <ImageCard key={e.uid} timestamp={e.imageUpdateDate} url={e.url}/>
        ))}
      </Main>
    </Root>
  )
}

const Main = styled.main`
  display: flex;
  flex-direction: row;
  flex-wrap: wrap;
  justify-content: center;
`

const Root = styled.div`
  @import url('https://fonts.googleapis.com/css2?family=Dosis:wght@300;400;600;800&display=swap');

  * {
    font-family: 'Dosis', sans-serif;
  }
`;
